create table plrti.past_history
(
	patientid integer not null
		constraint past_history_patientid
			unique,
	cureno integer not null
		constraint past_history_cureno
			unique,
	patientname varchar(64) not null,
	age double precision not null,
	sex varchar(64) not null,
	diagnoses varchar(256) not null,
	chief_complaints text not null,
	antibiotics_before_admission varchar(64),
	antibiotic_categories varchar(256),
	corticosteroid_medication_before_admission varchar(64),
	infectious_diseases_history varchar(64),
	which_infectious_disease varchar(256),
	tuberculosis_exposure_history varchar(64),
	vaccination_history varchar(256),
	streptococcus_pneumoniae_vaccination varchar(64),
	surgery_and_injury_history text,
	blood_transfusion_history varchar(256),
	drug_and_food_allergy varchar(64),
	eczema_history varchar(64),
	milk_protein_allergy varchar(64),
	allergic_rhinitis varchar(64),
	covid_19_infection_history varchar(64),
	chronic_respiratory_diseases varchar(64),
	recurrent_respiratory_tract_infection varchar(64),
	number_of_upper_respiratory_tract_infections_in_past_year integer,
	number_of_lower_respiratory_tract_infections_in_past_year integer,
	times_of_hospitalization_for_respiratory_diseases integer,
	times_of_oxygen_therapy integer,
	times_of_icu_stay integer,
	number_of_tracheal_intubations integer,
	other_basic_respiratory_disease varchar(64),
	severe_respiratory_diseases varchar(64),
	other_basic_disease varchar(64),
	wheeze_history varchar(64),
	first_wheezing integer,
	number_of_wheezes_in_2_years integer,
	number_of_wheezes_in_1_years integer,
	number_of_wheezes integer,
	precipitating_factor_for_wheeze varchar(256),
	allergen_induced_wheezing varchar(64),
	therapeutic_effect_of_diastolic_agent_for_wheeze varchar(64),
	test_of_serum_ige varchar(64),
	skin_prink_test varchar(64),
	allergen varchar(256),
	diagnosed_asthma_by_doctors varchar(64),
	start_date_of_asthma_treatment date,
	asthma_medication varchar(256),
	medication_compliance varchar(64),
	asthma_control varchar(64),
	gestation double precision,
	parity double precision,
	mode_of_delivery varchar(64),
	asphyxiation varchar(64),
	birth_weight double precision,
	feeding_mode varchar(64),
	add_complementary_food varchar(256),
	growth_and_development varchar(256),
	paternal_age double precision,
	paternal_occupation varchar(256),
	maternal_age double precision,
	maternal_occupation varchar(256),
	paternal_health_condition varchar(64),
	maternal_health_condition varchar(64),
	family_members_health_condition varchar(64),
	smoking_exposure varchar(64)
);

alter table plrti.past_history owner to postgres;

