create table plrti.pathogen
(
	patientid integer not null
		constraint pathogen_patientid
			unique,
	cureno integer not null
		constraint pathogen_cureno
			unique,
	patientname varchar(64) not null,
	age double precision not null,
	sex varchar(64) not null,
	acinetobacter_baumannii varchar(64),
	group_a_streptococcus varchar(64),
	bordetella_pertussis varchar(64),
	staphylococcus_epidermidis varchar(64),
	viridans_streptococci varchar(64),
	enterobacter_aerogenes varchar(64),
	klebsiella_oxytoca varchar(64),
	escherichia_coli varchar(64),
	finegoldia_magna varchar(64),
	nontyphoidal_salmonellosis varchar(64),
	klebsiella_pneumoniae varchar(64),
	pneumococcus varchar(64),
	enterococcus_faecalis varchar(64),
	pyogenic_streptococcus varchar(64),
	c_pseudodiphtheriticum varchar(64),
	campylobacter_ureolyticus varchar(64),
	staphylococcus_aureus varchar(64),
	moraxella_catarrhails varchar(64),
	oral_streptococci varchar(64),
	haemophilus_influenzae varchar(64),
	neisseria_meningitidis varchar(64),
	pandora_bacteria varchar(64),
	streptococcus_mitior varchar(64),
	acinetobacter varchar(64),
	staphylococcus_hominis varchar(64),
	staphylococcus varchar(64),
	salmonella varchar(64),
	enterococcus_faecium varchar(64),
	legionella_pneumophila varchar(64),
	stenotrophomonas_maltophilia varchar(64),
	pseudomonas_aeruginosa varchar(64),
	campylobacter varchar(64),
	malassezia_restricta varchar(64),
	burkholderia_cepacia varchar(64),
	enterobacter_cloacae varchar(64),
	serratia_marcescens varchar(64),
	shigella varchar(64),
	cytomegalovirus varchar(64),
	epstein_barrvirus varchar(64),
	rhinovirus varchar(64),
	bocavirus varchar(64),
	enterovirus varchar(64),
	herpes_simplex_virus varchar(64),
	parainfluenza_virus varchar(64),
	coronavirus varchar(64),
	hantavirus varchar(64),
	respiratory_syncytial_virus varchar(64),
	influenza_a_virus varchar(64),
	coxsackievirus varchar(64),
	influenza_b_virus varchar(64),
	rotavirus varchar(64),
	human_metapneumovirus varchar(64),
	varicella_zoster_virus varchar(64),
	parvovirus varchar(64),
	adenovirus varchar(64),
	erythromycin_resistant_group_a_streptococcus varchar(64),
	methicillin_resistant_staphylococcus_aureus varchar(64),
	drug_resistant_streptococcus_pneumoniae varchar(64),
	esbl_producing_escherichia_coli varchar(64),
	multidrug_resistant_acinetobacter varchar(64),
	carbapenem_resistant_enterobacterium varchar(64),
	mycoplasma varchar(64),
	fungus varchar(64),
	mycobacterium_tuberculosis varchar(64),
	chlamydia varchar(64),
	pertussis varchar(64)
);

alter table plrti.pathogen owner to postgres;

